<?php
/**
 * Comprou Também
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category   Ziny
 * @package    ComprouTambem
 * @copyright  Copyright (c) 2015 Agência Ziny (www.agenciaziny.com.br)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Agência Ziny <dev@agenciaziny.com.br>
 */
$produtos = $this->produtosComprados();
?>
<?php if ($this->ativo() && count($produtos)): ?>
    <div class="box-collateral box-up-sell">
        <h2><?php echo $this->titulo(); ?></h2>
        <ul class="products-grid products-grid--max-<?php echo $this->colunas(); ?>-col" id="upsell-product-table">
            <?php foreach ($produtos as $_index => $_item): ?>
                <li>
                    <a href="<?php echo $_item->getProductUrl(); ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(280); ?>" alt="<?php echo $this->htmlEscape($_item->getName()); ?>" />
                    </a>
                    <h3 class="product-name"><a href="<?php echo $_item->getProductUrl(); ?>"><?php echo $this->htmlEscape($_item->getName()); ?></a></h3>
                    <?php if ($this->preco()): ?>
                        <?php echo $this->getPriceHtml($_item); ?>
                    <?php endif; ?>
                    <?php if ($this->helper('wishlist')->isAllow()): ?>
                        <a href="<?php echo $this->getAddToWishlistUrl($_item); ?>" class="link-cart"><?php echo $this->__('Add to Wishlist'); ?></a>
                    <?php endif; ?>
                    <?php if ($_item->isSaleable()): ?>
                        <div class="clear"></div>
                        <a href="<?php echo $this->getAddToCartUrl($_item); ?>" class="link-cart"><?php echo $this->__('Add to Cart'); ?></a>
                    <?php endif; ?>
                </li>        
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
