<?php
/**
 * Comprou Também
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category   Ziny
 * @package    ComprouTambem
 * @copyright  Copyright (c) 2015 Agência Ziny (www.agenciaziny.com.br)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Agência Ziny <dev@agenciaziny.com.br>
 */
$produtos = $this->produtosComprados();
?>
<?php if ($this->configura('ativo') && count($produtos)): ?>
    <div class="box-collateral box-up-sell">
        <h2><?php echo $this->configura('titulo'); ?></h2>
        <ul class="products-grid products-grid--max-<?php echo $this->configura('colunas'); ?>-col" id="upsell-product-table">
            <?php foreach ($produtos as $_index => $_item): ?>
                <li>
                    <a href="<?php echo $_item->getProductUrl(); ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(280); ?>" alt="<?php echo $this->htmlEscape($_item->getName()); ?>" />
                    </a>
                    <h3 class="product-name"><a href="<?php echo $_item->getProductUrl(); ?>"><?php echo $this->htmlEscape($_item->getName()); ?></a></h3>
                    <?php if ($this->configura('preco')): ?>
                        <?php echo $this->getPriceHtml($_item); ?>
                    <?php endif; ?>                    
                    <?php if ($_item->isSaleable()): ?>
                        <div class="clear"></div>
                        <p class="action">
                            <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')); ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item); ?>')">
                                <span>
                                    <span><?php echo $this->__('Add to Cart'); ?></span>
                                </span>
                            </button>
                        </p>
                    <?php endif; ?>
                    <?php if ($this->helper('wishlist')->isAllow() && $this->configura('desejos')) : ?>
                        <p class="action"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_item); ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist'); ?></a></p>
                    <?php endif; ?>
                    <?php if (($_compareUrl = $this->getAddToCompareUrl($_item)) && $this->configura('compara')): ?>
                        <p class="action"><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare'); ?></a></p>
                    <?php endif; ?>
                </li>        
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>